[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins.inputs]]
  package = "@netlify/plugin-nextjs"
  command = "build"
  prebuild = "npm install @types/react-redux"
